{"04c3f5e2ca4d2406a8e07173a8e5d6a3":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"ecae78f0d05666f2","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/ecae78f0d05666f2","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c873b6690>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100599565,"stop":1689100599567,"duration":2}},{"uid":"bee99c18010c658e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/bee99c18010c658e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984e31290>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100069023,"stop":1689100069026,"duration":3}},{"uid":"d38df12dfe9ace74","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/d38df12dfe9ace74","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8c6b790>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099695034,"stop":1689099695038,"duration":4}},{"uid":"b161533fd0f6b1ad","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/b161533fd0f6b1ad","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d446590>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463598,"stop":1689099463601,"duration":3}}]},"3d8c2310dcdf0fa09ef77963288beaae":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"7a8c753ef1354c79","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/7a8c753ef1354c79","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/logout/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c8738b410>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100598490,"stop":1689100598491,"duration":1}},{"uid":"16c4fdaa1fb3ceb5","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/16c4fdaa1fb3ceb5","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/logout/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984e3ff10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100067910,"stop":1689100067912,"duration":2}},{"uid":"e65cb6cd3b836fcb","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/e65cb6cd3b836fcb","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/logout/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8267110>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099693712,"stop":1689099693714,"duration":2}},{"uid":"4e9845a0875b0478","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4e9845a0875b0478","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/logout/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d3af450>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462477,"stop":1689099462478,"duration":1}}]},"c2faddcaa5c781a3d469cb2b110469cc":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"22d48e9ae196e80b","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/22d48e9ae196e80b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c873869d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100598603,"stop":1689100598606,"duration":3}},{"uid":"289d36eb51a07aee","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/289d36eb51a07aee","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984e3bbd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100068026,"stop":1689100068029,"duration":3}},{"uid":"92a239c274d9c746","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/92a239c274d9c746","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8263310>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099693853,"stop":1689099693856,"duration":3}},{"uid":"7125474be6513c8d","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/7125474be6513c8d","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d3aae50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462594,"stop":1689099462597,"duration":3}}]},"12b8b637aa4c2d424e0f293f6e1a6261":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"465c711d09568695","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/465c711d09568695","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c876e2990>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100598246,"stop":1689100598248,"duration":2}},{"uid":"ec299161f71cc1f","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/ec299161f71cc1f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff98512e110>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100067660,"stop":1689100067664,"duration":4}},{"uid":"a85b57f1444431b8","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/a85b57f1444431b8","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d85ae6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099693410,"stop":1689099693414,"duration":4}},{"uid":"eae4bef8e478f784","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/eae4bef8e478f784","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d756490>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462226,"stop":1689099462229,"duration":3}}]},"b16bab1bf26416be8b02b5b57ad8c2ff":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"2b070ba4ab69cf11","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/2b070ba4ab69cf11","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c87441250>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100600175,"stop":1689100600176,"duration":1}},{"uid":"1c6cd56f0de74235","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/1c6cd56f0de74235","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984d70ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100069642,"stop":1689100069644,"duration":2}},{"uid":"750f66760de3ddd7","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/750f66760de3ddd7","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d85ada10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099695771,"stop":1689099695773,"duration":2}},{"uid":"8cc43a81d33e6587","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/8cc43a81d33e6587","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d8b0fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464218,"stop":1689099464220,"duration":2}}]},"f7c390d7cc3597e5887f346dfd836f72":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"fb7b1bd8c7e42769","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/fb7b1bd8c7e42769","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c87378d10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100599814,"stop":1689100599817,"duration":3}},{"uid":"ec9ab9261e34aa9b","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/ec9ab9261e34aa9b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984ee2610>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100069275,"stop":1689100069278,"duration":3}},{"uid":"b322da9137153a55","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/b322da9137153a55","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d832eb90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099695334,"stop":1689099695337,"duration":3}},{"uid":"b280fb59696c961c","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/b280fb59696c961c","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d416650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463851,"stop":1689099463854,"duration":3}}]},"bdecc3c5cafe3f9ebebb59a04f24e6b8":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"16dafa58847328bb","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/16dafa58847328bb","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/me/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c87492c50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100597889,"stop":1689100597891,"duration":2}},{"uid":"220f5dcdd2b1659","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/220f5dcdd2b1659","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/me/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984fcb490>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100067300,"stop":1689100067302,"duration":2}},{"uid":"94ca2a84b1e02d21","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/94ca2a84b1e02d21","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/me/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8616910>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099692974,"stop":1689099692976,"duration":2}},{"uid":"d0f134bc9783cb4e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/d0f134bc9783cb4e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/me/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d51f550>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461860,"stop":1689099461862,"duration":2}}]},"0c41c7377d01db82d03d4698b1ca5133":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"563234e19c365a6f","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/563234e19c365a6f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c87466f50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100597294,"stop":1689100597296,"duration":2}},{"uid":"ecb8922fae6934af","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/ecb8922fae6934af","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff98523d390>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100066686,"stop":1689100066687,"duration":1}},{"uid":"185a8f5e4e5e86a1","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/185a8f5e4e5e86a1","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8576ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099692238,"stop":1689099692240,"duration":2}},{"uid":"10225744bc2101ba","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/10225744bc2101ba","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d4928d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461239,"stop":1689099461241,"duration":2}}]},"320ac8f8d0d99852391a7b3854d421cf":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"52ecce2894567e55","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/52ecce2894567e55","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c874f5350>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100600404,"stop":1689100600405,"duration":1}},{"uid":"ad9b3d2c1de94b8","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/ad9b3d2c1de94b8","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984e81690>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100069874,"stop":1689100069876,"duration":2}},{"uid":"cc2bfb7bec2b94a0","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/cc2bfb7bec2b94a0","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d855ecd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099696056,"stop":1689099696058,"duration":2}},{"uid":"388f3a4618c37520","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/388f3a4618c37520","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d53e590>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464454,"stop":1689099464456,"duration":2}}]},"c10642315bdc1772ce7d3e4eca2b01fb":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"4f1b449f94df0869","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/4f1b449f94df0869","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c8744d450>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100598963,"stop":1689100598964,"duration":1}},{"uid":"ee66a53b0a3f7c21","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/ee66a53b0a3f7c21","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984f04f50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100068408,"stop":1689100068410,"duration":2}},{"uid":"4be625f2e75a5526","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4be625f2e75a5526","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8311c10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099694300,"stop":1689099694302,"duration":2}},{"uid":"c09c410dff25a4d9","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/c09c410dff25a4d9","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d478fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462965,"stop":1689099462967,"duration":2}}]},"597ae4f0152cb7f437f4ec96794fa1d8":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"8f87b61b0b2649e5","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/8f87b61b0b2649e5","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/download_shopping_cart/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c87492010>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100601254,"stop":1689100601256,"duration":2}},{"uid":"695bf2f0544ac361","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/695bf2f0544ac361","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/download_shopping_cart/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984ca9590>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100070750,"stop":1689100070751,"duration":1}},{"uid":"84f126aefa557ecf","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/84f126aefa557ecf","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/download_shopping_cart/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d855ce10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099697107,"stop":1689099697109,"duration":2}},{"uid":"3fff66743086d996","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/3fff66743086d996","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/download_shopping_cart/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d25e610>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465337,"stop":1689099465339,"duration":2}}]},"4d8270dc613966068cdf37650e0c3f1b":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"1321b6d8d1b9d80a","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/1321b6d8d1b9d80a","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c874e2b50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100597651,"stop":1689100597653,"duration":2}},{"uid":"8354bf8ff9ca4988","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/8354bf8ff9ca4988","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984fa0150>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100067053,"stop":1689100067055,"duration":2}},{"uid":"c8365b40510c4709","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/c8365b40510c4709","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d85a3bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099692682,"stop":1689099692684,"duration":2}},{"uid":"45ace8b2687d9b7c","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/45ace8b2687d9b7c","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d4ff9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461614,"stop":1689099461615,"duration":1}}]},"b222afed1bbb12d08851e139dfd328c1":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"7329641a805c8526","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/7329641a805c8526","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c87792690>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100599451,"stop":1689100599453,"duration":2}},{"uid":"9b5501a5dee29b56","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/9b5501a5dee29b56","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984d6f1d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100068908,"stop":1689100068910,"duration":2}},{"uid":"68359fe759d8a5d8","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/68359fe759d8a5d8","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d81913d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099694897,"stop":1689099694899,"duration":2}},{"uid":"149dd58dc9520245","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/149dd58dc9520245","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d2ddf10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463478,"stop":1689099463480,"duration":2}}]},"b834b96496eaf5ec890561b9bb9c2b13":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"1dcc368046d4015e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/1dcc368046d4015e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c87593d50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100599681,"stop":1689100599684,"duration":3}},{"uid":"78077b8db340102a","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/78077b8db340102a","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9850f2550>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100069140,"stop":1689100069144,"duration":4}},{"uid":"1d2da096401436f1","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/1d2da096401436f1","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8266b10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099695175,"stop":1689099695178,"duration":3}},{"uid":"e01f02cf59646b0e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/e01f02cf59646b0e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d32f8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463717,"stop":1689099463720,"duration":3}}]},"ed973a1c6247e086e2ca7b67f8861f99":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"9539488ff76c540b","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/9539488ff76c540b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c89558110>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100597029,"stop":1689100597032,"duration":3}},{"uid":"c53994fd8b3859fd","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/c53994fd8b3859fd","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff986e2c910>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100066392,"stop":1689100066395,"duration":3}},{"uid":"5232bd49c43a58fc","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/5232bd49c43a58fc","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8c7d810>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099691911,"stop":1689099691914,"duration":3}},{"uid":"f37dd23307146b58","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/f37dd23307146b58","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9eb712d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099460947,"stop":1689099460949,"duration":2}}]},"136fdf1cbe0628ab86cd5878f203a373":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"af520623018920af","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/af520623018920af","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c8715d6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100601500,"stop":1689100601502,"duration":2}},{"uid":"b9d097708603f537","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/b9d097708603f537","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984c39510>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100070994,"stop":1689100070996,"duration":2}},{"uid":"550c9e8273a735f","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/550c9e8273a735f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8556590>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099697406,"stop":1689099697408,"duration":2}},{"uid":"3311017f57eae875","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/3311017f57eae875","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d199690>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465594,"stop":1689099465595,"duration":1}}]},"c2adbfbbd491c2597b0fda673439e511":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"fdd67401fcfb612d","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/fdd67401fcfb612d","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c877261d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100597778,"stop":1689100597780,"duration":2}},{"uid":"9c4db10931f7dc55","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/9c4db10931f7dc55","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9851498d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100067185,"stop":1689100067187,"duration":2}},{"uid":"74720b4364e6b52b","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/74720b4364e6b52b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d83b9dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099692838,"stop":1689099692840,"duration":2}},{"uid":"e81ec34786e32f8a","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/e81ec34786e32f8a","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d744c90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461745,"stop":1689099461746,"duration":1}}]},"2c484cb66dc66302baa17f225812f595":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"a985048ef7500b78","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/a985048ef7500b78","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/set_password/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c8767a690>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100598131,"stop":1689100598132,"duration":1}},{"uid":"5b76d4055090f7d5","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/5b76d4055090f7d5","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/set_password/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9852b5450>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100067547,"stop":1689100067548,"duration":1}},{"uid":"4e41404dbfc6b0ca","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4e41404dbfc6b0ca","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/set_password/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d86e25d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099693272,"stop":1689099693274,"duration":2}},{"uid":"a5b8613002237dde","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/a5b8613002237dde","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/set_password/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d7de490>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462109,"stop":1689099462111,"duration":2}}]},"614551ca7970e22e71d92ff29a709595":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"387f537606f9470d","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/387f537606f9470d","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c87190ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100601614,"stop":1689100601615,"duration":1}},{"uid":"e1cbc3438e9d173","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/e1cbc3438e9d173","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984ebfe50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100071108,"stop":1689100071109,"duration":1}},{"uid":"eff3cd5c723f7903","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/eff3cd5c723f7903","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d82b3310>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099697544,"stop":1689099697546,"duration":2}},{"uid":"51a14ba5304f1ade","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/51a14ba5304f1ade","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d29b390>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465712,"stop":1689099465713,"duration":1}}]},"5d1ba22e143d84f83c3ace0980e350d4":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"80e1534b239d4777","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/80e1534b239d4777","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c871c2610>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100601367,"stop":1689100601370,"duration":3}},{"uid":"70e1a9e9244322d9","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/70e1a9e9244322d9","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984c3e690>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100070860,"stop":1689100070863,"duration":3}},{"uid":"ffa2ec82801f740d","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/ffa2ec82801f740d","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8130950>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099697243,"stop":1689099697247,"duration":4}},{"uid":"f65d34a6299a2366","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/f65d34a6299a2366","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d1f9350>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465452,"stop":1689099465455,"duration":3}}]},"f27bc5b997e6f4038ef2c5a6bf35e262":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"1703a2fbf9bb8d6b","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/1703a2fbf9bb8d6b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c8741f090>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100598850,"stop":1689100598852,"duration":2}},{"uid":"fa3d639c3ecaedc7","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/fa3d639c3ecaedc7","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984ed2dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100068291,"stop":1689100068292,"duration":1}},{"uid":"4859ac2f947fd29","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4859ac2f947fd29","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d82f9fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099694161,"stop":1689099694163,"duration":2}},{"uid":"12f53ebabc9f87e9","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/12f53ebabc9f87e9","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d442dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462849,"stop":1689099462850,"duration":1}}]},"07cd58bcb29a137195fe207cd8cf4156":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"3d3b7e2328b20ad9","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/3d3b7e2328b20ad9","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c8748b390>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100600043,"stop":1689100600046,"duration":3}},{"uid":"390cc9869cbf732b","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/390cc9869cbf732b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984db7650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100069507,"stop":1689100069510,"duration":3}},{"uid":"ae163107242bc8f","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/ae163107242bc8f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d82a8ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099695611,"stop":1689099695615,"duration":4}},{"uid":"649f41824447023d","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/649f41824447023d","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d464f90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464085,"stop":1689099464088,"duration":3}}]},"8bb43b26ad1d96a78a3961b3077bee32":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"634e913fd0a6cd8f","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/634e913fd0a6cd8f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c87633a50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100597181,"stop":1689100597183,"duration":2}},{"uid":"4f06ef9e5f834a73","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/4f06ef9e5f834a73","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9850e6590>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100066573,"stop":1689100066575,"duration":2}},{"uid":"904d3562cdb4d046","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/904d3562cdb4d046","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8517dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099692101,"stop":1689099692103,"duration":2}},{"uid":"e16b4c19c666b053","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/e16b4c19c666b053","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d6575d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461124,"stop":1689099461126,"duration":2}}]},"68a2c7a9203c112407f758b4272d49a6":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"b825d2d6fb982f03","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/b825d2d6fb982f03","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c87151210>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100601856,"stop":1689100601858,"duration":2}},{"uid":"d95a21318689e4ef","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/d95a21318689e4ef","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984cbd510>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100071359,"stop":1689100071360,"duration":1}},{"uid":"9c360686f70b0f3b","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/9c360686f70b0f3b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d804e450>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099697841,"stop":1689099697843,"duration":2}},{"uid":"84768b3fb43bf72e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/84768b3fb43bf72e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d226550>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465963,"stop":1689099465965,"duration":2}}]},"8ff593a56c4b3218c5c7be797b996bb4":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"70028612a6c8c03e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/70028612a6c8c03e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c874c2890>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100597537,"stop":1689100597540,"duration":3}},{"uid":"274ae8c62b9cd711","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/274ae8c62b9cd711","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984f6a610>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100066935,"stop":1689100066938,"duration":3}},{"uid":"4dab91050c2346f2","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4dab91050c2346f2","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8555f90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099692540,"stop":1689099692544,"duration":4}},{"uid":"918ced5319770fca","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/918ced5319770fca","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d4d9f10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461492,"stop":1689099461495,"duration":3}}]},"4df2eef17fb723554959c68ea1793cf3":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"7c8b336a24d9b839","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/7c8b336a24d9b839","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c873f7810>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100598735,"stop":1689100598738,"duration":3}},{"uid":"f59234008e0958bd","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/f59234008e0958bd","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984eabe10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100068170,"stop":1689100068173,"duration":3}},{"uid":"318835a6b7648fbb","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/318835a6b7648fbb","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d82d04d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099694017,"stop":1689099694021,"duration":4}},{"uid":"b6deb582fcab0814","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/b6deb582fcab0814","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d41bdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462731,"stop":1689099462734,"duration":3}}]},"6bbf5dca39d77801411a2696df165a23":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"4418e2322267ee95","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/4418e2322267ee95","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c87268790>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100599205,"stop":1689100599208,"duration":3}},{"uid":"8c3d7fe9a41bdc75","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/8c3d7fe9a41bdc75","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9851b0450>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100068656,"stop":1689100068659,"duration":3}},{"uid":"4ae7f4a2888461bf","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4ae7f4a2888461bf","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8253210>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099694598,"stop":1689099694602,"duration":4}},{"uid":"467d429b7bba4278","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/467d429b7bba4278","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d28cd10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463219,"stop":1689099463222,"duration":3}}]},"7c85eb922c681fbdd70cc78d116d1dc4":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"dedc021dfdae444a","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/dedc021dfdae444a","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c8724fd10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100599093,"stop":1689100599094,"duration":1}},{"uid":"8551af41f4614e31","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/8551af41f4614e31","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984d01f10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100068543,"stop":1689100068545,"duration":2}},{"uid":"a0be7152a74d5d63","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/a0be7152a74d5d63","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8398bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099694461,"stop":1689099694463,"duration":2}},{"uid":"3ada954aabb7fab","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/3ada954aabb7fab","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d3ab8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463102,"stop":1689099463104,"duration":2}}]},"6fee54b13e232dc877b90502b117f1b8":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"b62814101fbac910","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/b62814101fbac910","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c87209050>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100600892,"stop":1689100600893,"duration":1}},{"uid":"8b986d0b1cec25c4","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/8b986d0b1cec25c4","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984d3e210>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100070378,"stop":1689100070380,"duration":2}},{"uid":"c3f5bd7c50d85444","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/c3f5bd7c50d85444","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d81de2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099696655,"stop":1689099696657,"duration":2}},{"uid":"390e4d12932519c2","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/390e4d12932519c2","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d2a0f50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464961,"stop":1689099464963,"duration":2}}]},"18f81c631f68676ddc55a3e4d49da9c7":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"208699cafdbd4a6a","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/208699cafdbd4a6a","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c873d4090>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100601139,"stop":1689100601142,"duration":3}},{"uid":"1227d1682966a64d","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/1227d1682966a64d","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff98517a810>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100070635,"stop":1689100070638,"duration":3}},{"uid":"c0cc0c6f74d96b7f","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/c0cc0c6f74d96b7f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d814b2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099696964,"stop":1689099696968,"duration":4}},{"uid":"852fb49ed7e5fe3f","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/852fb49ed7e5fe3f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d1f5e90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465218,"stop":1689099465221,"duration":3}}]},"73faf4ff75facc1ada4c99bd363df620":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"6f3b81867a28f876","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/6f3b81867a28f876","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c8729f8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100599320,"stop":1689100599323,"duration":3}},{"uid":"482e744eb4d43807","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/482e744eb4d43807","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff98558ee90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100068772,"stop":1689100068775,"duration":3}},{"uid":"bbf951a990936e02","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/bbf951a990936e02","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d81742d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099694738,"stop":1689099694741,"duration":3}},{"uid":"7d50763b1f2b36f1","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/7d50763b1f2b36f1","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d2c0290>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463338,"stop":1689099463341,"duration":3}}]},"c3e68df8cccb43ad311c77d8989df80c":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"cb64df2146984c3c","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/cb64df2146984c3c","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c876e8a50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100597423,"stop":1689100597426,"duration":3}},{"uid":"531dce401e5e33b8","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/531dce401e5e33b8","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9851b1950>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100066818,"stop":1689100066821,"duration":3}},{"uid":"e22e5082db548fa1","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/e22e5082db548fa1","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d835ea90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099692398,"stop":1689099692402,"duration":4}},{"uid":"1c16db6f433ceab5","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/1c16db6f433ceab5","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d676f50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461373,"stop":1689099461377,"duration":4}}]},"b1fc92bb811b4a1bcef076e074cd3369":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"a9d2cc8e2995a6c","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/a9d2cc8e2995a6c","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c87ab0210>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100600531,"stop":1689100600534,"duration":3}},{"uid":"98db82f72bf8c87f","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/98db82f72bf8c87f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984f31290>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100070004,"stop":1689100070007,"duration":3}},{"uid":"b7b7605a9fd1e11e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/b7b7605a9fd1e11e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d832c410>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099696213,"stop":1689099696216,"duration":3}},{"uid":"f67d4122ef73410a","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/f67d4122ef73410a","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d416850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464587,"stop":1689099464590,"duration":3}}]},"19ffdcefa3b9df970185d80f63b32d70":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"daacb58f3beb3854","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/daacb58f3beb3854","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/subscriptions/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c87378750>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100600647,"stop":1689100600648,"duration":1}},{"uid":"739ce9b89c4eeb44","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/739ce9b89c4eeb44","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/subscriptions/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984d4d750>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100070121,"stop":1689100070122,"duration":1}},{"uid":"6304fd1714e2f212","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/6304fd1714e2f212","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/subscriptions/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d838be90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099696353,"stop":1689099696355,"duration":2}},{"uid":"5f0b1775022936dd","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/5f0b1775022936dd","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/subscriptions/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d2f2810>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464706,"stop":1689099464708,"duration":2}}]},"6216d5120ac0239aab4d58de3351c7c5":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"ced50123e2dd09f8","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/ced50123e2dd09f8","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c87862590>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100599930,"stop":1689100599931,"duration":1}},{"uid":"c05fef710d09f05","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/c05fef710d09f05","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984dc4050>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100069394,"stop":1689100069395,"duration":1}},{"uid":"bbbce940213dd6c4","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/bbbce940213dd6c4","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8793b10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099695474,"stop":1689099695476,"duration":2}},{"uid":"47510904f8fd8eb1","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/47510904f8fd8eb1","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d335590>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463969,"stop":1689099463970,"duration":1}}]},"b7d9874195a95979ffa8a88c67ae5aba":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"8e51011fe1b727a5","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/8e51011fe1b727a5","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c87189e50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100601005,"stop":1689100601008,"duration":3}},{"uid":"e58334bc00f339a0","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/e58334bc00f339a0","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984ca58d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100070497,"stop":1689100070500,"duration":3}},{"uid":"2df3d577e532adbb","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/2df3d577e532adbb","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8145850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099696795,"stop":1689099696798,"duration":3}},{"uid":"4fe004f44616e07e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4fe004f44616e07e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d248b90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465079,"stop":1689099465082,"duration":3}}]},"f2280457ffd433e4572bf538c4b03a78":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"564bdd59eae1fa0b","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/564bdd59eae1fa0b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c876a6150>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100600289,"stop":1689100600292,"duration":3}},{"uid":"8c2aef0fa3068bb1","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/8c2aef0fa3068bb1","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984ee3510>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100069759,"stop":1689100069762,"duration":3}},{"uid":"67c70e4eb540ef3b","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/67c70e4eb540ef3b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8439150>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099695914,"stop":1689099695918,"duration":4}},{"uid":"2dcd31a4f9e0ecf0","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/2dcd31a4f9e0ecf0","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d689350>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464333,"stop":1689099464337,"duration":4}}]},"b326a8ce65cd93d89129056abf81fa8b":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"e26800d3cbc54962","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/e26800d3cbc54962","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c8739c610>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100598361,"stop":1689100598364,"duration":3}},{"uid":"3ad02b8575ce5eed","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/3ad02b8575ce5eed","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984e53f90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100067776,"stop":1689100067780,"duration":4}},{"uid":"80f091d31ecf0318","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/80f091d31ecf0318","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d827a850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099693553,"stop":1689099693557,"duration":4}},{"uid":"e97c5b3c3a03a4c4","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/e97c5b3c3a03a4c4","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d3c0410>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462345,"stop":1689099462348,"duration":3}}]},"73d6b215df134dbc7235023eaa36add9":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"22a242c6f4a7b1ef","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/22a242c6f4a7b1ef","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c8750d410>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100598001,"stop":1689100598004,"duration":3}},{"uid":"aa2467838e7b526b","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/aa2467838e7b526b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff98519c110>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100067414,"stop":1689100067417,"duration":3}},{"uid":"7b33b73d52108549","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/7b33b73d52108549","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d840cb50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099693114,"stop":1689099693118,"duration":4}},{"uid":"a2451ac6e0d5e76f","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/a2451ac6e0d5e76f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d6d3c50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461976,"stop":1689099461979,"duration":3}}]},"4414e0858f9bd3714e43755837dfe2fc":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"abfb659e139c7df2","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/abfb659e139c7df2","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c871a5010>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100600777,"stop":1689100600780,"duration":3}},{"uid":"351fcbb74543782f","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/351fcbb74543782f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff985535450>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100070258,"stop":1689100070261,"duration":3}},{"uid":"2609cf7cf2320934","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/2609cf7cf2320934","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d80b5210>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099696514,"stop":1689099696518,"duration":4}},{"uid":"8efa1ac43c542b6a","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/8efa1ac43c542b6a","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d560b50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464843,"stop":1689099464846,"duration":3}}]},"4d022a96d12cb447a3eb1179e94870a4":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"1af2d28e15e11629","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/1af2d28e15e11629","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/99/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c874416d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100601969,"stop":1689100601971,"duration":2}},{"uid":"14e18708ac6557dd","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/14e18708ac6557dd","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/99/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984dc3610>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100071472,"stop":1689100071474,"duration":2}},{"uid":"c09d30db1e8092a6","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/c09d30db1e8092a6","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/99/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d823e510>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099697978,"stop":1689099697980,"duration":2}},{"uid":"4415c3c9718e11fc","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4415c3c9718e11fc","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/99/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d7e3850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099466079,"stop":1689099466081,"duration":2}}]},"adf9e8f1ccaef70993531bf3a2a95b28":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"d8ffc55e747b6505","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/d8ffc55e747b6505","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/123/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6c877eae90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100601726,"stop":1689100601727,"duration":1}},{"uid":"bf5b59d0b8856219","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/6//#testresult/bf5b59d0b8856219","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/123/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff984c14810>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689100071220,"stop":1689100071222,"duration":2}},{"uid":"12c603d75930087","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/12c603d75930087","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/123/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d869a850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099697680,"stop":1689099697682,"duration":2}},{"uid":"19e0e923a731dff1","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/19e0e923a731dff1","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/123/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d83ef90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465828,"stop":1689099465830,"duration":2}}]}}