{"uid":"b66e2c1c6c818e60","name":"test_negative_download_shopping_cart_not_logged","fullName":"tests.test_shopping_list.TestShoppingCart#test_negative_download_shopping_cart_not_logged","historyId":"597ae4f0152cb7f437f4ec96794fa1d8","time":{"start":1689190008069,"stop":1689190008071,"duration":2},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/download_shopping_cart/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f299b2c7490>: Failed to establish a new connection: [Errno 111] Connection refused'))","statusTrace":"E   ConnectionRefusedError: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f299b2c7490>: Failed to establish a new connection: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/download_shopping_cart/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f299b2c7490>: Failed to establish a new connection: [Errno 111] Connection refused'))\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/download_shopping_cart/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f299b2c7490>: Failed to establish a new connection: [Errno 111] Connection refused'))","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"story","value":"Тест скачивания списка покупок, без авторизации"},{"name":"feature","value":"Тесты добавления рецептов в список покупок."},{"name":"tag","value":"test_negative_download_shopping_cart_not_logged"},{"name":"tag","value":"shopping_cart_tests(scope='class')"},{"name":"tag","value":"order(5)"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_shopping_list"},{"name":"subSuite","value":"TestShoppingCart"},{"name":"host","value":"fv-az262-296"},{"name":"thread","value":"2338-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_shopping_list"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"8077b44e4908f379","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/26//#testresult/8077b44e4908f379","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/download_shopping_cart/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f8afc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689189538199,"stop":1689189538200,"duration":1}}]},"tags":["shopping_cart_tests(scope='class')","test_negative_download_shopping_cart_not_logged","order(5)"]},"source":"b66e2c1c6c818e60.json","parameterValues":[]}