{"uid":"f3ede33e732bef7a","name":"test_get_current_user","fullName":"tests.test_users.TestUsers#test_get_current_user","historyId":"c2adbfbbd491c2597b0fda673439e511","time":{"start":1689185539589,"stop":1689185539591,"duration":2},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957264f50>: Failed to establish a new connection: [Errno 111] Connection refused'))","statusTrace":"E   ConnectionRefusedError: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb957264f50>: Failed to establish a new connection: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957264f50>: Failed to establish a new connection: [Errno 111] Connection refused'))\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957264f50>: Failed to establish a new connection: [Errno 111] Connection refused'))","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"story","value":"Тест получения информации о текущем пользователе."},{"name":"feature","value":"Тесты работы с пользователем."},{"name":"tag","value":"test_get_current_user"},{"name":"tag","value":"users_tests(scope='class')"},{"name":"tag","value":"order(1)"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_users"},{"name":"subSuite","value":"TestUsers"},{"name":"host","value":"fv-az507-433"},{"name":"thread","value":"2317-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_users"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["test_get_current_user","order(1)","users_tests(scope='class')"]},"source":"f3ede33e732bef7a.json","parameterValues":[]}