{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb958240c10>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_users_list","uid":"67d341bb1bd97e16","parentUid":"2240f2761a4679a34180a661c5d883e8","status":"broken","time":{"start":1689185539504,"stop":1689185539507,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"2240f2761a4679a34180a661c5d883e8"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957234f90>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_user_registration","uid":"3926c69433be3f08","parentUid":"6b75d0b272578421fe559bf6e773f8b1","status":"broken","time":{"start":1689185539543,"stop":1689185539545,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"6b75d0b272578421fe559bf6e773f8b1"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957203710>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_user_registration","uid":"3090f00e322148e3","parentUid":"9b5809fa0347b028b3b6bfd939ee5c6b","status":"broken","time":{"start":1689185539551,"stop":1689185539554,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"9b5809fa0347b028b3b6bfd939ee5c6b"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957240510>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_user_profile","uid":"797b3669c2987ee1","parentUid":"ea084a6201821c0f97fba500b07ea052","status":"broken","time":{"start":1689185539560,"stop":1689185539564,"duration":4},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"ea084a6201821c0f97fba500b07ea052"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb95725de90>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_nagative_get_user_profile_object_not_found","uid":"867b042d5027ddd","parentUid":"a580b4d73e708b371fb6bcb76a45a527","status":"broken","time":{"start":1689185539571,"stop":1689185539574,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"a580b4d73e708b371fb6bcb76a45a527"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957202dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_get_user_profile_not_logged","uid":"cc24086b12ff93aa","parentUid":"228c6ea9da543ac91292b9d4d37bf99f","status":"broken","time":{"start":1689185539581,"stop":1689185539582,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"228c6ea9da543ac91292b9d4d37bf99f"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957264f50>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_current_user","uid":"f3ede33e732bef7a","parentUid":"e9f9b6fe8d9fbb5dffed442c2f1993a8","status":"broken","time":{"start":1689185539589,"stop":1689185539591,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"e9f9b6fe8d9fbb5dffed442c2f1993a8"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/me/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb95725ef10>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_get_current_user","uid":"fd70c6b6e6237d2","parentUid":"b1e843e94e1b3c2ddadcfd44a480af04","status":"broken","time":{"start":1689185539598,"stop":1689185539599,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"b1e843e94e1b3c2ddadcfd44a480af04"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9572701d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_changing_password","uid":"e1ce6f10dff785f6","parentUid":"4e2adf642f22d856f2dffdcf2b391f20","status":"broken","time":{"start":1689185539606,"stop":1689185539609,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"4e2adf642f22d856f2dffdcf2b391f20"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/set_password/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957272390>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_changing_password_user_not_logged","uid":"10f043bb91eb0333","parentUid":"89aa2016d8ceb4a52d22eedb417486ca","status":"broken","time":{"start":1689185539616,"stop":1689185539617,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"89aa2016d8ceb4a52d22eedb417486ca"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb95727a5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_changing_password_validation_error","uid":"804a61227d292edf","parentUid":"322cc960c38d2fe2796bdd71674633e1","status":"broken","time":{"start":1689185539624,"stop":1689185539627,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"322cc960c38d2fe2796bdd71674633e1"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb95725c610>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_delete_token","uid":"892b1a2a1efb54d9","parentUid":"55da58568a395f55e69186c6497e5012","status":"broken","time":{"start":1689185539634,"stop":1689185539637,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"55da58568a395f55e69186c6497e5012"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/logout/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9572850d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_delete_token_user_not_logged","uid":"8b88c6e4d03bf478","parentUid":"b3091a90e2005d58880c43cf53ad7e47","status":"broken","time":{"start":1689185539643,"stop":1689185539645,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"b3091a90e2005d58880c43cf53ad7e47"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957280bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_create_recipe","uid":"377ab978ab151b37","parentUid":"4b50802910b560e8e9dfb33b30cc04b2","status":"broken","time":{"start":1689185539651,"stop":1689185539655,"duration":4},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"4b50802910b560e8e9dfb33b30cc04b2"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb95728fa50>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_create_recipe_validation_error","uid":"976d62db9b15671","parentUid":"9a74d2c759edde9672f2d1543260c64b","status":"broken","time":{"start":1689185539661,"stop":1689185539664,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"9a74d2c759edde9672f2d1543260c64b"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957286050>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_create_recipe_user_not_logged","uid":"1a2c42cf99de9ca8","parentUid":"476f3e1af56b228a11119e00a04843f5","status":"broken","time":{"start":1689185539672,"stop":1689185539673,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"476f3e1af56b228a11119e00a04843f5"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb95727aa90>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_recipe","uid":"4832b0b4898adf61","parentUid":"e520c2b7cf86e609a0aa65256bb22b96","status":"broken","time":{"start":1689185539680,"stop":1689185539681,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"e520c2b7cf86e609a0aa65256bb22b96"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb95727bb10>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_recipes_list","uid":"d3025f074cd14be8","parentUid":"511141e01978b487000b6b5af8c11c21","status":"broken","time":{"start":1689185539687,"stop":1689185539689,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"511141e01978b487000b6b5af8c11c21"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957270d50>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_patch_recipe","uid":"4bd2192c4d0570b6","parentUid":"fe05ae363ca7f262379455eca27e7a23","status":"broken","time":{"start":1689185539695,"stop":1689185539699,"duration":4},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"fe05ae363ca7f262379455eca27e7a23"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957240450>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_patch_recipe_validation_error","uid":"8c6c9079a9f19aec","parentUid":"950f115fbaa2cfbbe4bd897d1d7d357b","status":"broken","time":{"start":1689185539705,"stop":1689185539709,"duration":4},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"950f115fbaa2cfbbe4bd897d1d7d357b"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb957279810>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_patch_recipe_user_not_logged","uid":"12a02595af37c44c","parentUid":"ab6bee94eda87ccf3bfa00a902852ef3","status":"broken","time":{"start":1689185539715,"stop":1689185539717,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"ab6bee94eda87ccf3bfa00a902852ef3"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb95729ca90>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_delete_recipe","uid":"295577f2c334eb26","parentUid":"98d4c4599c3daa9699290be990661263","status":"broken","time":{"start":1689185539723,"stop":1689185539727,"duration":4},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"98d4c4599c3daa9699290be990661263"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9574b14d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_add_recipe_favorites","uid":"e96a1c60bdc317b9","parentUid":"f0fd06bab7802c4db5ef9d33ff368264","status":"broken","time":{"start":1689185539733,"stop":1689185539737,"duration":4},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"f0fd06bab7802c4db5ef9d33ff368264"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb95729ffd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_add_recipe_favorites_validation_error","uid":"14d473b72f0be955","parentUid":"3e94f214a5a422815784584c405bb599","status":"broken","time":{"start":1689185539743,"stop":1689185539747,"duration":4},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"3e94f214a5a422815784584c405bb599"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9572a5e90>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_add_recipe_favorites_user_not_logged","uid":"69902de2a2edec3f","parentUid":"83cffdeeede2d624a4eb8d5d289c0606","status":"broken","time":{"start":1689185539753,"stop":1689185539755,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"83cffdeeede2d624a4eb8d5d289c0606"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9572aa2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_recipe_delete_favorites","uid":"b5cada095701f3c7","parentUid":"ff0a608eaf149e941abd56b3555ddbe1","status":"broken","time":{"start":1689185539762,"stop":1689185539765,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"ff0a608eaf149e941abd56b3555ddbe1"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9572ac290>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_recipe_delete_favorites_user_not_logged","uid":"88489a4008579b1e","parentUid":"380b8e6c8086c93427e7284b5c518b86","status":"broken","time":{"start":1689185539772,"stop":1689185539773,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"380b8e6c8086c93427e7284b5c518b86"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9572b07d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_subscribe_to_user","uid":"e8cef8937f229c7d","parentUid":"a14fb4e1db1cf1adfb413709a966ab33","status":"broken","time":{"start":1689185539780,"stop":1689185539783,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"a14fb4e1db1cf1adfb413709a966ab33"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9572a5050>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_subscribe_to_user_not_logged","uid":"34003a82c1b0edf6","parentUid":"b48dfaf52e78f8693dccbb70e00a6d80","status":"broken","time":{"start":1689185539790,"stop":1689185539791,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"b48dfaf52e78f8693dccbb70e00a6d80"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570bedd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_subscriptions","uid":"d0798ab86575ec7b","parentUid":"89f2909b82f74c967e3b530ce2a33806","status":"broken","time":{"start":1689185539798,"stop":1689185539801,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"89f2909b82f74c967e3b530ce2a33806"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/subscriptions/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9572b3510>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_subscriptions_user_not_logged","uid":"5a049b09dfb90a21","parentUid":"0b704f47dfffc070d3f4141230d451b5","status":"broken","time":{"start":1689185539807,"stop":1689185539809,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"0b704f47dfffc070d3f4141230d451b5"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570cd590>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_unsubscribe_to_user","uid":"25a1ef88d22ec64e","parentUid":"b5eedc4e96bdb995a5745642f258c620","status":"broken","time":{"start":1689185539815,"stop":1689185539819,"duration":4},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"b5eedc4e96bdb995a5745642f258c620"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570bdad0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_unsubscribe_error","uid":"6239161800139aee","parentUid":"31a30fd460437b085c1a304e8f33ba88","status":"broken","time":{"start":1689185539825,"stop":1689185539827,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"31a30fd460437b085c1a304e8f33ba88"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570dffd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_add_shopping_cart","uid":"b7185f7a6c8e0f64","parentUid":"5d6372672b7aa2905c7e793b21714e5a","status":"broken","time":{"start":1689185539833,"stop":1689185539836,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"5d6372672b7aa2905c7e793b21714e5a"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570ce010>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_download_shopping_cart","uid":"a937cb01a3ac5be4","parentUid":"7f42fee417e4cf081362b813dbffd2a5","status":"broken","time":{"start":1689185539843,"stop":1689185539846,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"7f42fee417e4cf081362b813dbffd2a5"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/download_shopping_cart/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570eaa90>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_download_shopping_cart_not_logged","uid":"7e146181bc6c75bf","parentUid":"3d5fe6ba4ea770022a727c12496b3093","status":"broken","time":{"start":1689185539853,"stop":1689185539854,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"3d5fe6ba4ea770022a727c12496b3093"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570e26d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_delete_shopping_cart","uid":"a36dac0cb7ef4f96","parentUid":"7c353c5d0d47e8388f7cd243cd501548","status":"broken","time":{"start":1689185539861,"stop":1689185539864,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"7c353c5d0d47e8388f7cd243cd501548"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570f9050>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_delete_shopping_cart_not_logged","uid":"66570e5f19124ddb","parentUid":"030b75e3e49abf8e8ad8b1eec3071559","status":"broken","time":{"start":1689185539870,"stop":1689185539872,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"030b75e3e49abf8e8ad8b1eec3071559"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570f1c50>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_ingredients_list","uid":"32b0180766b843c6","parentUid":"53a71d712688f944a41e10c8e6c6784b","status":"broken","time":{"start":1689185539879,"stop":1689185539880,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"53a71d712688f944a41e10c8e6c6784b"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/123/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570ff5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_ingredient","uid":"c8d0941cd4708c8c","parentUid":"19a1fcab7c4082a9c082df65f6ac27fe","status":"broken","time":{"start":1689185539887,"stop":1689185539888,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"19a1fcab7c4082a9c082df65f6ac27fe"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570f9a50>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_tags_list","uid":"bf45bd7ba0d165e8","parentUid":"c4db377766de33ed28bc577e03a60a93","status":"broken","time":{"start":1689185539896,"stop":1689185539898,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"c4db377766de33ed28bc577e03a60a93"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/99/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb9570e8390>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_tags_not_found","uid":"2fbe43c8f4a5c72e","parentUid":"919bc57d40db705093a14ace0a93ab8a","status":"broken","time":{"start":1689185539904,"stop":1689185539905,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"919bc57d40db705093a14ace0a93ab8a"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}