{"04c3f5e2ca4d2406a8e07173a8e5d6a3":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"d38df12dfe9ace74","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/d38df12dfe9ace74","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8c6b790>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099695034,"stop":1689099695038,"duration":4}},{"uid":"b161533fd0f6b1ad","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/b161533fd0f6b1ad","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d446590>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463598,"stop":1689099463601,"duration":3}}]},"3d8c2310dcdf0fa09ef77963288beaae":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"e65cb6cd3b836fcb","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/e65cb6cd3b836fcb","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/logout/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8267110>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099693712,"stop":1689099693714,"duration":2}},{"uid":"4e9845a0875b0478","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4e9845a0875b0478","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/logout/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d3af450>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462477,"stop":1689099462478,"duration":1}}]},"c2faddcaa5c781a3d469cb2b110469cc":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"92a239c274d9c746","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/92a239c274d9c746","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8263310>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099693853,"stop":1689099693856,"duration":3}},{"uid":"7125474be6513c8d","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/7125474be6513c8d","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d3aae50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462594,"stop":1689099462597,"duration":3}}]},"12b8b637aa4c2d424e0f293f6e1a6261":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"a85b57f1444431b8","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/a85b57f1444431b8","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d85ae6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099693410,"stop":1689099693414,"duration":4}},{"uid":"eae4bef8e478f784","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/eae4bef8e478f784","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d756490>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462226,"stop":1689099462229,"duration":3}}]},"b16bab1bf26416be8b02b5b57ad8c2ff":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"750f66760de3ddd7","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/750f66760de3ddd7","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d85ada10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099695771,"stop":1689099695773,"duration":2}},{"uid":"8cc43a81d33e6587","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/8cc43a81d33e6587","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d8b0fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464218,"stop":1689099464220,"duration":2}}]},"f7c390d7cc3597e5887f346dfd836f72":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"b322da9137153a55","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/b322da9137153a55","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d832eb90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099695334,"stop":1689099695337,"duration":3}},{"uid":"b280fb59696c961c","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/b280fb59696c961c","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d416650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463851,"stop":1689099463854,"duration":3}}]},"bdecc3c5cafe3f9ebebb59a04f24e6b8":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"94ca2a84b1e02d21","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/94ca2a84b1e02d21","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/me/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8616910>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099692974,"stop":1689099692976,"duration":2}},{"uid":"d0f134bc9783cb4e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/d0f134bc9783cb4e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/me/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d51f550>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461860,"stop":1689099461862,"duration":2}}]},"0c41c7377d01db82d03d4698b1ca5133":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"185a8f5e4e5e86a1","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/185a8f5e4e5e86a1","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8576ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099692238,"stop":1689099692240,"duration":2}},{"uid":"10225744bc2101ba","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/10225744bc2101ba","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d4928d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461239,"stop":1689099461241,"duration":2}}]},"320ac8f8d0d99852391a7b3854d421cf":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"cc2bfb7bec2b94a0","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/cc2bfb7bec2b94a0","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d855ecd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099696056,"stop":1689099696058,"duration":2}},{"uid":"388f3a4618c37520","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/388f3a4618c37520","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d53e590>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464454,"stop":1689099464456,"duration":2}}]},"c10642315bdc1772ce7d3e4eca2b01fb":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"4be625f2e75a5526","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4be625f2e75a5526","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8311c10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099694300,"stop":1689099694302,"duration":2}},{"uid":"c09c410dff25a4d9","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/c09c410dff25a4d9","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d478fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462965,"stop":1689099462967,"duration":2}}]},"597ae4f0152cb7f437f4ec96794fa1d8":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"84f126aefa557ecf","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/84f126aefa557ecf","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/download_shopping_cart/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d855ce10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099697107,"stop":1689099697109,"duration":2}},{"uid":"3fff66743086d996","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/3fff66743086d996","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/download_shopping_cart/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d25e610>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465337,"stop":1689099465339,"duration":2}}]},"4d8270dc613966068cdf37650e0c3f1b":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"c8365b40510c4709","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/c8365b40510c4709","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d85a3bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099692682,"stop":1689099692684,"duration":2}},{"uid":"45ace8b2687d9b7c","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/45ace8b2687d9b7c","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d4ff9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461614,"stop":1689099461615,"duration":1}}]},"b222afed1bbb12d08851e139dfd328c1":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"68359fe759d8a5d8","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/68359fe759d8a5d8","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d81913d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099694897,"stop":1689099694899,"duration":2}},{"uid":"149dd58dc9520245","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/149dd58dc9520245","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d2ddf10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463478,"stop":1689099463480,"duration":2}}]},"b834b96496eaf5ec890561b9bb9c2b13":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"1d2da096401436f1","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/1d2da096401436f1","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8266b10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099695175,"stop":1689099695178,"duration":3}},{"uid":"e01f02cf59646b0e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/e01f02cf59646b0e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d32f8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463717,"stop":1689099463720,"duration":3}}]},"ed973a1c6247e086e2ca7b67f8861f99":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"5232bd49c43a58fc","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/5232bd49c43a58fc","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8c7d810>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099691911,"stop":1689099691914,"duration":3}},{"uid":"f37dd23307146b58","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/f37dd23307146b58","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9eb712d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099460947,"stop":1689099460949,"duration":2}}]},"136fdf1cbe0628ab86cd5878f203a373":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"550c9e8273a735f","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/550c9e8273a735f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8556590>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099697406,"stop":1689099697408,"duration":2}},{"uid":"3311017f57eae875","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/3311017f57eae875","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d199690>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465594,"stop":1689099465595,"duration":1}}]},"c2adbfbbd491c2597b0fda673439e511":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"74720b4364e6b52b","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/74720b4364e6b52b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d83b9dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099692838,"stop":1689099692840,"duration":2}},{"uid":"e81ec34786e32f8a","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/e81ec34786e32f8a","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d744c90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461745,"stop":1689099461746,"duration":1}}]},"2c484cb66dc66302baa17f225812f595":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"4e41404dbfc6b0ca","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4e41404dbfc6b0ca","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/set_password/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d86e25d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099693272,"stop":1689099693274,"duration":2}},{"uid":"a5b8613002237dde","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/a5b8613002237dde","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/set_password/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d7de490>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462109,"stop":1689099462111,"duration":2}}]},"614551ca7970e22e71d92ff29a709595":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"eff3cd5c723f7903","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/eff3cd5c723f7903","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d82b3310>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099697544,"stop":1689099697546,"duration":2}},{"uid":"51a14ba5304f1ade","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/51a14ba5304f1ade","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d29b390>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465712,"stop":1689099465713,"duration":1}}]},"5d1ba22e143d84f83c3ace0980e350d4":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"ffa2ec82801f740d","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/ffa2ec82801f740d","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8130950>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099697243,"stop":1689099697247,"duration":4}},{"uid":"f65d34a6299a2366","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/f65d34a6299a2366","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d1f9350>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465452,"stop":1689099465455,"duration":3}}]},"f27bc5b997e6f4038ef2c5a6bf35e262":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"4859ac2f947fd29","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4859ac2f947fd29","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d82f9fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099694161,"stop":1689099694163,"duration":2}},{"uid":"12f53ebabc9f87e9","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/12f53ebabc9f87e9","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d442dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462849,"stop":1689099462850,"duration":1}}]},"07cd58bcb29a137195fe207cd8cf4156":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"ae163107242bc8f","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/ae163107242bc8f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d82a8ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099695611,"stop":1689099695615,"duration":4}},{"uid":"649f41824447023d","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/649f41824447023d","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d464f90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464085,"stop":1689099464088,"duration":3}}]},"8bb43b26ad1d96a78a3961b3077bee32":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"904d3562cdb4d046","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/904d3562cdb4d046","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8517dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099692101,"stop":1689099692103,"duration":2}},{"uid":"e16b4c19c666b053","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/e16b4c19c666b053","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d6575d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461124,"stop":1689099461126,"duration":2}}]},"68a2c7a9203c112407f758b4272d49a6":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"9c360686f70b0f3b","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/9c360686f70b0f3b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d804e450>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099697841,"stop":1689099697843,"duration":2}},{"uid":"84768b3fb43bf72e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/84768b3fb43bf72e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d226550>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465963,"stop":1689099465965,"duration":2}}]},"8ff593a56c4b3218c5c7be797b996bb4":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"4dab91050c2346f2","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4dab91050c2346f2","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8555f90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099692540,"stop":1689099692544,"duration":4}},{"uid":"918ced5319770fca","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/918ced5319770fca","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d4d9f10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461492,"stop":1689099461495,"duration":3}}]},"4df2eef17fb723554959c68ea1793cf3":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"318835a6b7648fbb","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/318835a6b7648fbb","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d82d04d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099694017,"stop":1689099694021,"duration":4}},{"uid":"b6deb582fcab0814","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/b6deb582fcab0814","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d41bdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462731,"stop":1689099462734,"duration":3}}]},"6bbf5dca39d77801411a2696df165a23":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"4ae7f4a2888461bf","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4ae7f4a2888461bf","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8253210>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099694598,"stop":1689099694602,"duration":4}},{"uid":"467d429b7bba4278","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/467d429b7bba4278","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d28cd10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463219,"stop":1689099463222,"duration":3}}]},"7c85eb922c681fbdd70cc78d116d1dc4":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"a0be7152a74d5d63","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/a0be7152a74d5d63","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8398bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099694461,"stop":1689099694463,"duration":2}},{"uid":"3ada954aabb7fab","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/3ada954aabb7fab","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d3ab8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463102,"stop":1689099463104,"duration":2}}]},"6fee54b13e232dc877b90502b117f1b8":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"c3f5bd7c50d85444","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/c3f5bd7c50d85444","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d81de2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099696655,"stop":1689099696657,"duration":2}},{"uid":"390e4d12932519c2","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/390e4d12932519c2","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d2a0f50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464961,"stop":1689099464963,"duration":2}}]},"18f81c631f68676ddc55a3e4d49da9c7":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"c0cc0c6f74d96b7f","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/c0cc0c6f74d96b7f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d814b2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099696964,"stop":1689099696968,"duration":4}},{"uid":"852fb49ed7e5fe3f","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/852fb49ed7e5fe3f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d1f5e90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465218,"stop":1689099465221,"duration":3}}]},"73faf4ff75facc1ada4c99bd363df620":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"bbf951a990936e02","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/bbf951a990936e02","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d81742d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099694738,"stop":1689099694741,"duration":3}},{"uid":"7d50763b1f2b36f1","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/7d50763b1f2b36f1","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d2c0290>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463338,"stop":1689099463341,"duration":3}}]},"c3e68df8cccb43ad311c77d8989df80c":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"e22e5082db548fa1","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/e22e5082db548fa1","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d835ea90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099692398,"stop":1689099692402,"duration":4}},{"uid":"1c16db6f433ceab5","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/1c16db6f433ceab5","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d676f50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461373,"stop":1689099461377,"duration":4}}]},"b1fc92bb811b4a1bcef076e074cd3369":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"b7b7605a9fd1e11e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/b7b7605a9fd1e11e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d832c410>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099696213,"stop":1689099696216,"duration":3}},{"uid":"f67d4122ef73410a","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/f67d4122ef73410a","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d416850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464587,"stop":1689099464590,"duration":3}}]},"19ffdcefa3b9df970185d80f63b32d70":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"6304fd1714e2f212","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/6304fd1714e2f212","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/subscriptions/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d838be90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099696353,"stop":1689099696355,"duration":2}},{"uid":"5f0b1775022936dd","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/5f0b1775022936dd","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/subscriptions/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d2f2810>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464706,"stop":1689099464708,"duration":2}}]},"6216d5120ac0239aab4d58de3351c7c5":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"bbbce940213dd6c4","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/bbbce940213dd6c4","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8793b10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099695474,"stop":1689099695476,"duration":2}},{"uid":"47510904f8fd8eb1","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/47510904f8fd8eb1","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d335590>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099463969,"stop":1689099463970,"duration":1}}]},"b7d9874195a95979ffa8a88c67ae5aba":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"2df3d577e532adbb","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/2df3d577e532adbb","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8145850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099696795,"stop":1689099696798,"duration":3}},{"uid":"4fe004f44616e07e","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4fe004f44616e07e","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d248b90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465079,"stop":1689099465082,"duration":3}}]},"f2280457ffd433e4572bf538c4b03a78":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"67c70e4eb540ef3b","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/67c70e4eb540ef3b","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d8439150>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099695914,"stop":1689099695918,"duration":4}},{"uid":"2dcd31a4f9e0ecf0","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/2dcd31a4f9e0ecf0","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d689350>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464333,"stop":1689099464337,"duration":4}}]},"b326a8ce65cd93d89129056abf81fa8b":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"80f091d31ecf0318","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/80f091d31ecf0318","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d827a850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099693553,"stop":1689099693557,"duration":4}},{"uid":"e97c5b3c3a03a4c4","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/e97c5b3c3a03a4c4","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d3c0410>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099462345,"stop":1689099462348,"duration":3}}]},"73d6b215df134dbc7235023eaa36add9":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"7b33b73d52108549","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/7b33b73d52108549","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d840cb50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099693114,"stop":1689099693118,"duration":4}},{"uid":"a2451ac6e0d5e76f","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/a2451ac6e0d5e76f","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d6d3c50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099461976,"stop":1689099461979,"duration":3}}]},"4414e0858f9bd3714e43755837dfe2fc":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"2609cf7cf2320934","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/2609cf7cf2320934","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d80b5210>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099696514,"stop":1689099696518,"duration":4}},{"uid":"8efa1ac43c542b6a","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/8efa1ac43c542b6a","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d560b50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099464843,"stop":1689099464846,"duration":3}}]},"4d022a96d12cb447a3eb1179e94870a4":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"c09d30db1e8092a6","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/c09d30db1e8092a6","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/99/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d823e510>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099697978,"stop":1689099697980,"duration":2}},{"uid":"4415c3c9718e11fc","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/4415c3c9718e11fc","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/99/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d7e3850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099466079,"stop":1689099466081,"duration":2}}]},"adf9e8f1ccaef70993531bf3a2a95b28":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"12c603d75930087","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/12c603d75930087","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/123/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f68d869a850>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099697680,"stop":1689099697682,"duration":2}},{"uid":"19e0e923a731dff1","reportUrl":"https://IlyaYaP.github.io/testing_api_foodgram/5//#testresult/19e0e923a731dff1","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/123/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda9d83ef90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1689099465828,"stop":1689099465830,"duration":2}}]}}