{"uid":"7daba21ddcfb7639","name":"test_negative_get_user_profile_not_logged","fullName":"tests.test_users.TestUsers#test_negative_get_user_profile_not_logged","historyId":"4d8270dc613966068cdf37650e0c3f1b","time":{"start":1689189537990,"stop":1689189537991,"duration":1},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f9ff2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","statusTrace":"E   ConnectionRefusedError: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb31f9ff2d0>: Failed to establish a new connection: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f9ff2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31f9ff2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"story","value":"Тест получения информации о пользователе, без авторизации."},{"name":"feature","value":"Тесты работы с пользователем."},{"name":"tag","value":"test_negative_get_user_profile_not_logged"},{"name":"tag","value":"users_tests(scope='class')"},{"name":"tag","value":"order(1)"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_users"},{"name":"subSuite","value":"TestUsers"},{"name":"host","value":"fv-az309-816"},{"name":"thread","value":"2346-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_users"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["order(1)","test_negative_get_user_profile_not_logged","users_tests(scope='class')"]},"source":"7daba21ddcfb7639.json","parameterValues":[]}