{"uid":"ba79b7aaeca149ac","name":"test_negative_create_recipe_user_not_logged","fullName":"tests.test_recipes.TestRecipeCreation#test_negative_create_recipe_user_not_logged","historyId":"f27bc5b997e6f4038ef2c5a6bf35e262","time":{"start":1689189538060,"stop":1689189538062,"duration":2},"status":"broken","statusMessage":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa4ded0>: Failed to establish a new connection: [Errno 111] Connection refused'))","statusTrace":"E   ConnectionRefusedError: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb31fa4ded0>: Failed to establish a new connection: [Errno 111] Connection refused\n\nThe above exception was the direct cause of the following exception:\nE   urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa4ded0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n\nDuring handling of the above exception, another exception occurred:\nE   requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb31fa4ded0>: Failed to establish a new connection: [Errno 111] Connection refused'))","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"story","value":"Тест создания рецепта, без авторизации."},{"name":"feature","value":"Тесты создания рецептов."},{"name":"tag","value":"test_negative_create_recipe_user_not_logged"},{"name":"tag","value":"recipe_creation_tests(scope='class')"},{"name":"tag","value":"order(2)"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_recipes"},{"name":"subSuite","value":"TestRecipeCreation"},{"name":"host","value":"fv-az309-816"},{"name":"thread","value":"2346-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_recipes"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["order(2)","test_negative_create_recipe_user_not_logged","recipe_creation_tests(scope='class')"]},"source":"ba79b7aaeca149ac.json","parameterValues":[]}