{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33abd8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_users_list","uid":"bb2ff1250726857a","parentUid":"0107e15484a97b41f4a8d22a2e721a73","status":"broken","time":{"start":1689187741396,"stop":1689187741399,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"0107e15484a97b41f4a8d22a2e721a73"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f331b5bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_user_registration","uid":"b7c71ff5e899a3c7","parentUid":"a2796c867a4232751d107830f3b3a351","status":"broken","time":{"start":1689187741415,"stop":1689187741416,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]},{"name":"test_negative_user_registration","uid":"bd5abbb515f4c712","parentUid":"a2796c867a4232751d107830f3b3a351","status":"broken","time":{"start":1689187741422,"stop":1689187741424,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"a2796c867a4232751d107830f3b3a351"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f331c1090>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_user_profile","uid":"be20ad741614f7b","parentUid":"47ab1fe8d11344acb1f3579f17465c35","status":"broken","time":{"start":1689187741429,"stop":1689187741433,"duration":4},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"47ab1fe8d11344acb1f3579f17465c35"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33467010>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_nagative_get_user_profile_object_not_found","uid":"7c367efe7acfdf17","parentUid":"0a9ec922738df60ed91107e223362e5f","status":"broken","time":{"start":1689187741438,"stop":1689187741441,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"0a9ec922738df60ed91107e223362e5f"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/1/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f3314fd50>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_get_user_profile_not_logged","uid":"d514e832a506bb71","parentUid":"c48e4ca12cdb280946fcda3f964977a9","status":"broken","time":{"start":1689187741447,"stop":1689187741448,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"c48e4ca12cdb280946fcda3f964977a9"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f331e5c50>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_current_user","uid":"4a48a10c6e50eaad","parentUid":"02721265001d24d820b47f31fde06f76","status":"broken","time":{"start":1689187741454,"stop":1689187741455,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"02721265001d24d820b47f31fde06f76"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/me/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f331e0bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_get_current_user","uid":"55fcb533a8ad50e","parentUid":"a7ab14eeda8e4984b2c6b883042659ff","status":"broken","time":{"start":1689187741461,"stop":1689187741462,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"a7ab14eeda8e4984b2c6b883042659ff"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f331f0ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_changing_password","uid":"b084c8045a5532c1","parentUid":"74c4e7038d203478c84b866576f343f0","status":"broken","time":{"start":1689187741468,"stop":1689187741470,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"74c4e7038d203478c84b866576f343f0"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/set_password/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f331f2090>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_changing_password_user_not_logged","uid":"9a2e18fb644ba84b","parentUid":"c53fee11e34ecd0d1a2d11f70d08607a","status":"broken","time":{"start":1689187741476,"stop":1689187741477,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"c53fee11e34ecd0d1a2d11f70d08607a"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f331f7250>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_changing_password_validation_error","uid":"9ab47add8bc3f1dc","parentUid":"75e974f7ab5cc865af1537b03423bec1","status":"broken","time":{"start":1689187741483,"stop":1689187741485,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"75e974f7ab5cc865af1537b03423bec1"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f331e0f90>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_delete_token","uid":"5ac8e4836ada5a2b","parentUid":"3f4ad8fdd62ab42a184a61e369ffd933","status":"broken","time":{"start":1689187741491,"stop":1689187741494,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"3f4ad8fdd62ab42a184a61e369ffd933"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/logout/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33201d90>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_delete_token_user_not_logged","uid":"c907777ec1493f84","parentUid":"64cf62398b5019cd11a0708281100231","status":"broken","time":{"start":1689187741499,"stop":1689187741500,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"64cf62398b5019cd11a0708281100231"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f331fe5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_create_recipe","uid":"7ac63fdf6bdfbf4b","parentUid":"75ab5b352c6ab7562228b62a303959b5","status":"broken","time":{"start":1689187741506,"stop":1689187741509,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"75ab5b352c6ab7562228b62a303959b5"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33210690>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_create_recipe_validation_error","uid":"4b6a7c8b4fb5d955","parentUid":"027e6fa984c8e921b36c475d6c5d8a9d","status":"broken","time":{"start":1689187741514,"stop":1689187741517,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"027e6fa984c8e921b36c475d6c5d8a9d"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33200a90>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_create_recipe_user_not_logged","uid":"855927d3a33629db","parentUid":"9ce2fbfc1a1634afd09595f84da05e4c","status":"broken","time":{"start":1689187741523,"stop":1689187741525,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"9ce2fbfc1a1634afd09595f84da05e4c"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f331f62d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_recipe","uid":"c05ec1426f4f6a70","parentUid":"bc00d953c4808cd0d6d5918ff2293c92","status":"broken","time":{"start":1689187741530,"stop":1689187741531,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"bc00d953c4808cd0d6d5918ff2293c92"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f331f7410>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_recipes_list","uid":"53fd492acd093a9e","parentUid":"95b84cb161273d0a6a6bc36718ac3c4e","status":"broken","time":{"start":1689187741537,"stop":1689187741538,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"95b84cb161273d0a6a6bc36718ac3c4e"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f331f1b90>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_patch_recipe","uid":"d5b23b7ddc2f8a4d","parentUid":"3edfe2a3adfc8fcdfb9d1dbbacfd6406","status":"broken","time":{"start":1689187741544,"stop":1689187741546,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"3edfe2a3adfc8fcdfb9d1dbbacfd6406"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f331e40d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_patch_recipe_validation_error","uid":"8dc2abf4989a4948","parentUid":"f0908c80754dee0d05c9d6e78cb7fa9a","status":"broken","time":{"start":1689187741552,"stop":1689187741555,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"f0908c80754dee0d05c9d6e78cb7fa9a"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f331f6810>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_patch_recipe_user_not_logged","uid":"e72d6060700f6ebd","parentUid":"8c1ce166bd736838f115c74253356c26","status":"broken","time":{"start":1689187741560,"stop":1689187741561,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"8c1ce166bd736838f115c74253356c26"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33219590>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_delete_recipe","uid":"7a731584e181adee","parentUid":"522e7c34e45155d0164df7e00b528f29","status":"broken","time":{"start":1689187741567,"stop":1689187741570,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"522e7c34e45155d0164df7e00b528f29"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33474d10>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_add_recipe_favorites","uid":"40fa2c251ea22dde","parentUid":"9697963445eaa6d01d85bdbaab590a2b","status":"broken","time":{"start":1689187741575,"stop":1689187741578,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"9697963445eaa6d01d85bdbaab590a2b"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33220b10>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_add_recipe_favorites_validation_error","uid":"177a5a773f2ccac0","parentUid":"30e9b345763f139db530f18ab3860672","status":"broken","time":{"start":1689187741583,"stop":1689187741586,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"30e9b345763f139db530f18ab3860672"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33222950>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_add_recipe_favorites_user_not_logged","uid":"4ac91bde82cc1772","parentUid":"3d2a154bcbed9efa96136a3193f7244d","status":"broken","time":{"start":1689187741592,"stop":1689187741593,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"3d2a154bcbed9efa96136a3193f7244d"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33226d90>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_recipe_delete_favorites","uid":"3d99a4513084612f","parentUid":"f9039cb999bbb1b903538d1bdea7d451","status":"broken","time":{"start":1689187741598,"stop":1689187741601,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"f9039cb999bbb1b903538d1bdea7d451"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33228d90>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_recipe_delete_favorites_user_not_logged","uid":"b08988120cd13aba","parentUid":"717158591f69c25a9d6170118e69c511","status":"broken","time":{"start":1689187741607,"stop":1689187741608,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"717158591f69c25a9d6170118e69c511"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f3322d2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_subscribe_to_user","uid":"ccc5e9f33b5e7778","parentUid":"e4f43d43c24202752209a6f145758b46","status":"broken","time":{"start":1689187741613,"stop":1689187741616,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"e4f43d43c24202752209a6f145758b46"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33221f10>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_subscribe_to_user_not_logged","uid":"ac948373403a06ef","parentUid":"1f8e0eb1055e88ecf83711e1cf535d6f","status":"broken","time":{"start":1689187741622,"stop":1689187741623,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"1f8e0eb1055e88ecf83711e1cf535d6f"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f3323f910>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_subscriptions","uid":"ad7d358ef506f32","parentUid":"ffef7e0f8761d65b7034e35266e60532","status":"broken","time":{"start":1689187741628,"stop":1689187741631,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"ffef7e0f8761d65b7034e35266e60532"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/subscriptions/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33229b50>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_subscriptions_user_not_logged","uid":"21cac4718dbc1305","parentUid":"f1b6952e38584ba1499beb87fc79e4ef","status":"broken","time":{"start":1689187741637,"stop":1689187741638,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"f1b6952e38584ba1499beb87fc79e4ef"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f330461d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_unsubscribe_to_user","uid":"65b876caaaecddcc","parentUid":"2e6902ca0302f700f2bc3943246c0db2","status":"broken","time":{"start":1689187741643,"stop":1689187741646,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"2e6902ca0302f700f2bc3943246c0db2"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/users/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f331e4a90>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_unsubscribe_error","uid":"81f0f8cb0902354b","parentUid":"d33ab15f0c58dc75e484a382e1423a2f","status":"broken","time":{"start":1689187741651,"stop":1689187741653,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"d33ab15f0c58dc75e484a382e1423a2f"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33058c50>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_add_shopping_cart","uid":"7e0c00dff78a17be","parentUid":"865bcad514e7a896b18a7501b206bdf5","status":"broken","time":{"start":1689187741658,"stop":1689187741661,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"865bcad514e7a896b18a7501b206bdf5"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33056490>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_download_shopping_cart","uid":"166295d4fa8a2edb","parentUid":"52944980eef9feb3866cce0978279d42","status":"broken","time":{"start":1689187741666,"stop":1689187741669,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"52944980eef9feb3866cce0978279d42"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/download_shopping_cart/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33063550>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_download_shopping_cart_not_logged","uid":"27d184090adc8dd2","parentUid":"85883282a0e3d3a2dd73aea5bcb2f443","status":"broken","time":{"start":1689187741675,"stop":1689187741676,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"85883282a0e3d3a2dd73aea5bcb2f443"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/auth/token/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f3305b5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_delete_shopping_cart","uid":"643f6d122f0233fa","parentUid":"fb75e05f09bbccd534d82d0b20bac270","status":"broken","time":{"start":1689187741681,"stop":1689187741684,"duration":3},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"fb75e05f09bbccd534d82d0b20bac270"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/recipes/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33071b90>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_delete_shopping_cart_not_logged","uid":"1e356b251a13f9a5","parentUid":"4d756257fc84eabdafca4364b290eb5a","status":"broken","time":{"start":1689187741689,"stop":1689187741691,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"4d756257fc84eabdafca4364b290eb5a"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f3306bed0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_ingredients_list","uid":"2dd4ed6c9fb5b51c","parentUid":"6b908d3de48e93bbd016ee251ff7ce54","status":"broken","time":{"start":1689187741696,"stop":1689187741698,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"6b908d3de48e93bbd016ee251ff7ce54"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/ingredients/123/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33080110>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_get_ingredient","uid":"ffa07de8e2cd75b9","parentUid":"9086fc710415e71858829a321fb2283e","status":"broken","time":{"start":1689187741703,"stop":1689187741704,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"9086fc710415e71858829a321fb2283e"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f33072110>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_tags_list","uid":"5fee56ed9dff7d17","parentUid":"61db5e98791b22c5a655003f6d824851","status":"broken","time":{"start":1689187741711,"stop":1689187741712,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"61db5e98791b22c5a655003f6d824851"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /api/tags/99/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3f330628d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_negative_tags_not_found","uid":"dcb593d049a8bb11","parentUid":"7e13f3a34cd967de9ac2bff49f4c31b7","status":"broken","time":{"start":1689187741717,"stop":1689187741719,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"7e13f3a34cd967de9ac2bff49f4c31b7"},{"name":"_pytest.fixtures.FixtureLookupError: ('self', <FixtureRequest for <Function test_create_recipe>>)","children":[{"name":"test_create_recipe","uid":"ffc00c06de919899","parentUid":"badf39694933678d08bbf085fbb75163","status":"broken","time":{"start":1689187741724,"stop":1689187741724,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"badf39694933678d08bbf085fbb75163"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}